### ISSUE TITLE
create 함수에서의 출력 부분

### ISSUE THREAD

**Issue by zzlhye0307** [Xayahx/ManageEverything#7]
contactCreate(), todoCreate(), appoCreate()에서 중복되는 name 혹은 title일 경우 
이미 존재합니다. 다시 입력하세요 라고 출력하는데 다시 입력할 기회를 제공하지 않고
1. Create, 2. View, 3. Update, 4. Delete, 5. Return to main" 이 출력되는 게 어색할 것 같아요.

아예 "다시 입력하세요." 라는 말을 출력하지 않는 게 어떨까요?

**Comment by Xayahx** [comment]
제 생각도 그래요! 그냥 title인 경우에는  That title already exists만 출력하고 name인 경우에는  That name already exists 만 출력하고 메뉴로 넘어가는 게 좋을 것 같아요.
